- components/FooterPaymentFormList.js
- components/FooterSocialNetworkList.js
- components/FooterVtexLogo.js
- components/footerList.js
- components/withImage.js
- global.css
- index.js
Fixing Footer's Design
Design problems:
https://lucianofooter--storecomponents.myvtex.com
> Fixing Footer's Design

- CHANGELOG.md
- manifest.json
- react/components/footerList.js
> Remove call to console.log

- CHANGELOG.md
- manifest.json
- react/global.css
- react/index.js
Replace the shadow in the bottom of the footer with a line
Resolve design issues
[Accessing this workspace](https://linefooter--storecomponents.myvtex.com/)
*Before*
*After*
> Replace shadow by line

- CHANGELOG.md
- manifest.json
- react/components/FooterVtexLogo.js
- react/components/footerList.js
- react/global.css
- react/index.js
- react/package.json
Padronize footer's paddings
FIx paddgins of footer
[Workspace](https://footerpadding--storecomponents.myvtex.com/)
Before
After
> Fix paddings of footer

- CHANGELOG.md
- manifest.json
- react/components/Accordion.js
Align vertically the footer links
Misalignment of the footer links
[Access this workspace](https://theoworkspace--storecomponents.myvtex.com/iphone-xs/p)
> Fix links alignment on footer

- CHANGELOG.md
- react/components/FooterLinkList.js
- react/components/FooterLinksMatrix.js
- react/components/FooterSocialNetworkList.js
- react/components/footerList.js
- react/index.js
Replace some Tachyons' CSS classes with the design tokens.
[Click here to access the workspace.](https://waza4--storecomponents.myvtex.com/)
> Replace some Tachyons' CSS classes with the design tokens

- CHANGELOG.md
- manifest.json
- react/components/FooterLinkList.js
fix: https://app.clubhouse.io/vtex-dev/story/2556/footer-is-interpolating-href-inside-class
> fix footer item class and link

- CHANGELOG.md
- manifest.json
- react/footer.css
- react/index.js
As the title says 
https://padding--storecomponents.myvtex.com/
> Fix component responsive behavior

- CHANGELOG.md
- manifest.json
- react/index.js
We have some technical debts when we talk about html structure from our components:
- Lacking HTML5 structural elements: nav, header, footer, main, section
This pr has a purpose to solve the problems above.
https://inlineblock--storecomponents.myvtex.com/
To help understand the html5 tags: https://webflow.com/blog/html5-semantic-elements-and-webflow-the-essential-guide
> Improve HTML code quality

- CHANGELOG.md
- manifest.json
- react/components/Accordion.js
As the title says
In mobile mode
https://icons--storecomponents.myvtex.com/
> Use icons from dreamstore-icons

- CHANGELOG.md
- manifest.json
> Release v2.6.1

- CHANGELOG.md
- manifest.json
- react/components/FooterSocialNetworkList.js
- react/footer.css
- react/index.js
Add missing css-handles in components in order to allow customization with CSS Modules. 
https://csshandles--storecomponents.myvtex.com/
> Add CSS Handles to allow customization by CSS Modules

- CHANGELOG.md
- manifest.json
> Release v2.6.5

- CHANGELOG.md
- README.md
- manifest.json
- react/footer.css
- react/index.js
As the title said. 
https://csshandles--storecomponents.myvtex.com/
> Fix typo in css handle token

- .travis.yml
- .vtexignore
- CHANGELOG.md
- README.md
- react/.babelrc
- react/__mocks__/vtex.dreamstore-icons.js
- react/__mocks__/vtex.render-runtime.js
- react/__mocks__/vtex.store-components.js
- react/__tests__/Footer.test.js
- react/__tests__/__snapshots__/Footer.test.js.snap
- react/package.json
- react/testUtils/setupTests.js
- react/testUtils/test-utils.js
- react/yarn.lock
> Add React testing library and Add Snapshot tests

- .gitignore
- .travis.yml
- .vtexignore
- README.md
- react/__tests__/Footer.test.js
- react/package.json
- react/yarn.lock
As described in the title.
Just run `yarn test` inside `react/`
> Upgrade test suite with more tests and add test coverage

- CHANGELOG.md
- manifest.json
- react/__tests__/__snapshots__/Footer.test.js.snap
- react/components/Accordion.js
- react/components/FooterLinkList.js
- react/components/FooterLinksMatrix.js
- react/components/FooterPaymentFormMatrix.js
- react/components/footerList.js
- react/index.js
As described in the title.
[Here](https://alves2--storecomponents.myvtex.com/)
Before
> Fix proptypes warnings

- react/components/FooterVtexLogo.js
- react/package.json
- react/yarn.lock
Use external validator to verify if account is from GoCommerce.
> Check if is GoCommerce from lib

- CHANGELOG.md
- manifest.json
- store/interfaces.json
> Allow adding flex-layout to footer

- CHANGELOG.md
- manifest.json
- react/typings/gocommerce.d.ts
Makes it pass in new babel 7, react3.x builder
> Makes it pass in new react3.x builder

- CHANGELOG.md
- manifest.json
- react/AcceptedPaymentMethods.tsx
- react/SocialNetworks.tsx
Remove React error.
Clean console from errors.
Compare 
https://breno--storecomponents.myvtex.com/
With
https://galc--storecomponents.myvtex.com/
> Fix React 'key' for SocialNetworks and AcceptedPaymentMethods

- CHANGELOG.md
- manifest.json
- react/legacy/FooterPaymentFormList.js
- react/legacy/FooterSocialNetworkList.js
As the title says
[workspace](https://fixlegacy--storecomponents.myvtex.com/)
> Use lowercase for assets in legacy footer

- CHANGELOG.md
- manifest.json
- react/.eslintrc
- react/.prettierrc
- react/AcceptedPaymentMethods.tsx
- react/Footer.js
- react/FooterLayout.tsx
- react/Row.tsx
- react/SocialNetworks.tsx
- react/__mocks__/vtex.native-types.tsx
- react/__mocks__/vtex.render-runtime.tsx
- react/components/PaymentMethodIcon.tsx
- react/components/SocialNetwork.tsx
- react/components/withImage.d.ts
- react/legacy/Accordion.js
- react/legacy/Footer.js
- react/legacy/Footer.test.js
- react/legacy/FooterLinkList.js
- react/legacy/__snapshots__/Footer.test.js.snap
- react/package.json
- react/typings/vtex.native-types.d.ts
- react/yarn.lock
- store/contentSchemas.json
- store/interfaces.json
Migrate non-layout schema to `contentSchemas.json`
:man_shrugging: 
[workspace](https://lucas2--storecomponents.myvtex.com/?cultureInfo=ja-JP).
> Add content schemas

- CHANGELOG.md
Force a new build with the latest builder-hub version.
Dynamic assets not being served through `vteximg`.
> Republish store footer

- CHANGELOG.md
- react/PoweredBy.tsx
Add hyperlink to GoCommerce logo. 
Related to https://app.clubhouse.io/vtex/story/14182/inserir-hyperlink-no-logo-do-rodap%C3%A9-do-storefront
https://augusto--madinejeans.mygocommerce.com/
> Add hyperlink to GoCommerce powered by logo

- README.md
Fix documentation.
It was giving wrong directions on how to customize footer css.
> Fix css instructions

- CHANGELOG.md
- store/interfaces.json
> Render lazy

- docs/README.md
Update README file with new CSS handles created by PR #90 .
Outdated docs. Should close https://github.com/vtex-apps/io-documentation/issues/382
> Update README with new CSS handles

- CHANGELOG.md
- react/package.json
- react/yarn.lock
- store/interfaces.json
https://fidheadfoot--alssports.myvtex.com/
https://fidheadfoot--storecomponents.myvtex.com/
https://fidheadfoot--boticario.myvtex.com/
https://fidheadfoot--tbb.myvtex.com/
https://fidheadfoot--exitocol.myvtex.com/
https://fidheadfoot--paguemenos.myvtex.com/
> add device values in interfaces json

- CHANGELOG.md
- react/PoweredBy.tsx
- react/__mocks__/vtex.render-runtime.tsx
- react/components/PaymentMethodIcon.tsx
- react/components/SocialNetwork.tsx
- react/typings/svg.d.ts
Remove lazy load from some components. Also removed legacy HoC components (`injectIntl`, `withRuntimeContext`) whenever possible.
This optimisation is kind of useless since the icons always appear and result in more requests:
> Remove lazy svg
